/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.crio.qcalc;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        StandardCalculator calc = new StandardCalculator();
        ScientificCalculator calc2 = new ScientificCalculator();
        calc.add(1,2);
        System.out.println(calc.getResult());
        calc.subtract(5,4);
        System.out.println(calc.getResult());
        calc.multiply(2,3);
        System.out.println(calc.getResult());
        calc.divide(4,2);
        System.out.println(calc.getResult());

        

        //double result= calc2.cubeOf(4.0);

        //System.out.println("cube =" + result);

        int result= calc2.modulo(5, 2);

        System.out.println("modulo =" + result);


       
    }
   
    
}

